# Reference: https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml
runtime: python
env: flex
# instance_class: F4
service: cannary-google-trace
entrypoint: gunicorn --worker-tmp-dir /dev/shm -b :$PORT app:app --workers=1 --threads=1

# handlers:
#   - url: .*
#     script: auto

# automatic_scaling:
#     min_instances: 1
#     max_instances: 5
runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 0.9
  disk_size_gb: 10

# Readiness checks confirm that an instance can accept incoming requests.
# Instances that don't pass the readiness check are not added to the pool of available instances.
readiness_check:
  path: /healthz
  check_interval_sec: 5
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 2000

# Liveness checks confirm that the VM and the Docker container are running.
# Instances that are deemed unhealthy are restarted.
liveness_check:
  path: /healthz
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 1800 # 15m
  max_concurrent_requests: 25
  max_pending_latency: automatic

network:
  name: default